import Head  from "next/head";

import Main from "@/styles/Homes.module.css";

import Topo   from "@/components/topo";
import Corpo  from "@/components/corpo";
import Rodape from "@/components/rodape";

export default function Home() {
return (
<div>
<Head>
<title>Create Next App</title>
<meta name="description" content="Generated by create next app" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link rel="icon" href="/favicon.ico" />
</Head>
 
<Topo/> 

<main className={Main.Body_Content}>
<Corpo/>
<Corpo/>
<Corpo/>
</main>

<Rodape/>

</div>
);
}
